### ISSUE TITLE
Why not to use dl.sitecore.net instead

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/OnTime-Accelerators-Download#1]
Why not to use http://dl.sitecore.net/updater/ontime.js instead?

**Comment by Zvirja** [comment]
Because browser extension will not be able to update the script later. That
happens because of the specific headers as far as I remember.

Currently, script is hosted in my local repo, but I want to move it out of
there.

If you see better place - offer it.

**Comment by AlenPelin** [comment]
ok
